export const BANDERAS: Record<string, string> = {
  México: "🇲🇽",
  "Corea del Sur": "🇰🇷",
  "República Checa": "🇨🇿",
  Sudáfrica: "🇿🇦",
  Canadá: "🇨🇦",
  "Bosnia y H.": "🇧🇦",
  Catar: "🇶🇦",
  Suiza: "🇨🇭",
  Brasil: "🇧🇷",
  Marruecos: "🇲🇦",
  Haití: "🇭🇹",
  Escocia: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Estados Unidos": "🇺🇸",
  Paraguay: "🇵🇾",
  Australia: "🇦🇺",
  Turquía: "🇹🇷",
  Alemania: "🇩🇪",
  Curazao: "🇨🇼",
  "Costa de Marfil": "🇨🇮",
  Ecuador: "🇪🇨",
  "Países Bajos": "🇳🇱",
  Japón: "🇯🇵",
  Suecia: "🇸🇪",
  Túnez: "🇹🇳",
  Bélgica: "🇧🇪",
  Egipto: "🇪🇬",
  Irán: "🇮🇷",
  "Nueva Zelanda": "🇳🇿",
  España: "🇪🇸",
  "Cabo Verde": "🇨🇻",
  "Arabia Saudita": "🇸🇦",
  Uruguay: "🇺🇾",
  Francia: "🇫🇷",
  Senegal: "🇸🇳",
  Irak: "🇮🇶",
  Noruega: "🇳🇴",
  Argentina: "🇦🇷",
  Argelia: "🇩🇿",
  Austria: "🇦🇹",
  Jordania: "🇯🇴",
  Portugal: "🇵🇹",
  "RD Congo": "🇨🇩",
  Uzbekistán: "🇺🇿",
  Colombia: "🇨🇴",
  Inglaterra: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  Croacia: "🇭🇷",
  Ghana: "🇬🇭",
  Panamá: "🇵🇦",
}
